### ISSUE TITLE
Override default error page

### ISSUE THREAD

**Issue by qazs** [feathersjs/errors#102]
Is there a way to override the default feathers error page?
Eg. Placing a custom 404.html in /public folder?

**Comment by daffl** [comment]
As mentioned in the [errorHandler API documentation](https://docs.feathersjs.com/api/express.html#appuseexpresserrorhandleroptions) you can either pass a middleware or a path to an HTML file. I just added an example how to pass files for each error code

```js
const { errorHandler } = require('@feathersjs/errors');
const app = feathers();

app.use(errorHandler({
    html: {
      404: 'path/to/notFound.html',
      500: 'there/will/be/robots.html'
    }
}));
```

**Comment by qazs** [comment]
Thanks, I tried your example but I get this error:
`TypeError: errorHandler is not a function`
Is it something I'm missing?

**Comment by daffl** [comment]
Oh yes, sorry it was `const { errorHandler } = require('@feathersjs/express');`, I fixed it in the examples as well.

**Comment by qazs** [comment]
Thanks! I got it to work using the previous code:
```
const handler = require('feathers-errors/handler');
const notFound = require('feathers-errors/not-found');

app.use(notFound());
app.use(handler({
  html: {
    401: app.get('public') + '/401.html',
    404: app.get('public') + '/404.html'
  }
}));
```

It's a bit confusing though as there are 2 feathers errors module, `@feathers/errors` and `feathers-errors`.  I went with the generator code and it's good.
