### ISSUE TITLE
Is Secure return error.data in production NODE_ENV ?

### ISSUE THREAD

**Issue by Bubomir** [feathersjs/errors#115]
Hi I am using error handler middleware for formating errors. 

    // last middleware 
    app.use(errorsHandler())

But I observing in NODE_ENV=production setting that if I call get service method feathers-sequelize on some database model for example products when i pass bad ID it will return response like:
    
    request [GET]:
    header['content-type']='application/json'
    localhost:3000/products/BAD_ID
    
    response:
    {
    "name": "NotFound",
    "message": "No record found for id '1a'",
    "code": 404,
    "className": "not-found",
    "data": {
        "name": "SequelizeDatabaseError",
        "parent": {
            "name": "error",
            "length": 97,
            "severity": "ERROR",
            "code": "22P02",
            "position": "885",
            "file": "numutils.c",
            "line": "106",
            "routine": "pg_atoi",
            "sql": "SELECT \"products\".\"id\", \"products\".\"name\", \"products\".\"description\", \"products\".\"link\", \"products\".\"modelSFBUrl\", \"products\".\"modelUrl\", \"products\".\"modelType\", \"category\".\"id\" AS \"category.id\", \"category\".\"name\" AS \"category.name\", \"category\".\"image\" AS \"category.image\", \"brand\".\"id\" AS \"brand.id\", \"brand\".\"name\" AS \"brand.name\", \"brand\".\"logo\" AS \"brand.logo\", \"brand->products\".\"id\" AS \"brand.products.id\", \"galleries\".\"id\" AS \"galleries.id\", \"galleries\".\"url\" AS \"galleries.url\" FROM \"products\" AS \"products\" LEFT OUTER JOIN \"categories\" AS \"category\" ON \"products\".\"categoryId\" = \"category\".\"id\" LEFT OUTER JOIN \"brands\" AS \"brand\" ON \"products\".\"brandId\" = \"brand\".\"id\" LEFT OUTER JOIN \"products\" AS \"brand->products\" ON \"brand\".\"id\" = \"brand->products\".\"brandId\" LEFT OUTER JOIN \"galleries\" AS \"galleries\" ON \"products\".\"id\" = \"galleries\".\"productId\" WHERE \"products\".\"id\" = '1a';"
        },
        "original": {
            "name": "error",
            "length": 97,
            "severity": "ERROR",
            "code": "22P02",
            "position": "885",
            "file": "numutils.c",
            "line": "106",
            "routine": "pg_atoi",
            "sql": "SELECT \"products\".\"id\", \"products\".\"name\", \"products\".\"description\", \"products\".\"link\", \"products\".\"modelSFBUrl\", \"products\".\"modelUrl\", \"products\".\"modelType\", \"category\".\"id\" AS \"category.id\", \"category\".\"name\" AS \"category.name\", \"category\".\"image\" AS \"category.image\", \"brand\".\"id\" AS \"brand.id\", \"brand\".\"name\" AS \"brand.name\", \"brand\".\"logo\" AS \"brand.logo\", \"brand->products\".\"id\" AS \"brand.products.id\", \"galleries\".\"id\" AS \"galleries.id\", \"galleries\".\"url\" AS \"galleries.url\" FROM \"products\" AS \"products\" LEFT OUTER JOIN \"categories\" AS \"category\" ON \"products\".\"categoryId\" = \"category\".\"id\" LEFT OUTER JOIN \"brands\" AS \"brand\" ON \"products\".\"brandId\" = \"brand\".\"id\" LEFT OUTER JOIN \"products\" AS \"brand->products\" ON \"brand\".\"id\" = \"brand->products\".\"brandId\" LEFT OUTER JOIN \"galleries\" AS \"galleries\" ON \"products\".\"id\" = \"galleries\".\"productId\" WHERE \"products\".\"id\" = '1a';"
        },
        "sql": "SELECT \"products\".\"id\", \"products\".\"name\", \"products\".\"description\", \"products\".\"link\", \"products\".\"modelSFBUrl\", \"products\".\"modelUrl\", \"products\".\"modelType\", \"category\".\"id\" AS \"category.id\", \"category\".\"name\" AS \"category.name\", \"category\".\"image\" AS \"category.image\", \"brand\".\"id\" AS \"brand.id\", \"brand\".\"name\" AS \"brand.name\", \"brand\".\"logo\" AS \"brand.logo\", \"brand->products\".\"id\" AS \"brand.products.id\", \"galleries\".\"id\" AS \"galleries.id\", \"galleries\".\"url\" AS \"galleries.url\" FROM \"products\" AS \"products\" LEFT OUTER JOIN \"categories\" AS \"category\" ON \"products\".\"categoryId\" = \"category\".\"id\" LEFT OUTER JOIN \"brands\" AS \"brand\" ON \"products\".\"brandId\" = \"brand\".\"id\" LEFT OUTER JOIN \"products\" AS \"brand->products\" ON \"brand\".\"id\" = \"brand->products\".\"brandId\" LEFT OUTER JOIN \"galleries\" AS \"galleries\" ON \"products\".\"id\" = \"galleries\".\"productId\" WHERE \"products\".\"id\" = '1a';"
    },
    "errors": {}
}

Is this a correct behaviour ? Is it a safe sending this kind of data in production env to a client? I checked the errorHandler source  code and I found that output.stack is removed if a NODE_ENV is a production but what about output.data ?

     if (process.env.NODE_ENV === 'production') {
            delete output.stack;
    }

Thanks for your opinion
 
### Expected behavior
Not sending data property in error response

### System configuration

Tell us about the applicable parts of your setup.

**Module versions** (especially the part that's not working):
@feathersjs/errors": "3.3.0
@feathersjs/express": "1.2.2
@feathersjs/feathers": "3.1.4
"feathers-sequelize": "3.1.0"

**NodeJS version**:
8.11.2

**Operating System**:
Win 10

**Comment by daffl** [comment]
This is a [feathers-sequelize](https://github.com/feathersjs-ecosystem/feathers-sequelize) adapter specific problem. The next breaking version will remove this behaviour but it can already be solved with an error hook like this:

```js
module.exports = () => {
  return async context => {
    const { error } = context;

    if (error.data && error.data.name === 'SequelizeDatabaseError') {
      context.error.data = {};
    }

    return context;
  };
};
```

**Comment by daffl** [comment]
Closing since there is a workaround as shown. The default behaviour will also be changed in the next version of `feathers-sequelize` (see linked issue).
