### ISSUE TITLE
Throwing error in async hook gives Unhandled Rejection error

### ISSUE THREAD

**Issue by shadowRR** [feathersjs/errors#116]
Hello,

I'm basically throwing an error in an async hook (validations error -> Unprocessable). 
While my hooks are stopped, and the client is getting the error properly, i'm also getting a Unhandled rejection on my server console ? I know i should have a handler on the global level (it's temporarily disabled while testing other stuff), but shouldn't feathers-errors have handled the error to avoid an 'Unhandled Rejection' showing up, since they are actually handled ?

```
exports.validate = function() {

  return async function( hook ) {

    hooks.checkContext( hook, 'before', [ 'create', 'patch' ], 'validate' );

    // i've removed query so it's easier to read
    const request = await hook.app.service( '/my/service' ).find( query );
    if ( request.length > 0 ) {
      errors_messages.push( 'error message here' );
    }

    // a few other similar validations requests here
    
    // if any validations errors we're found, throw
    if ( errors_messages.length > 0 ) {
      throw new errors.Unprocessable( 'ServerValidationsErrors', errors_messages );
    }

    return hook;
  };

};
```

I've tried by returning a `Promise.reject( new errors.Unprocessable( 'text' ) )`, but i've been getting the same result, and i don't see the point of wrapping it in a `try{} catch( err ){}`, which would mean handling the validations failure twice...

Thanks.

**Comment by daffl** [comment]
I can not reproduce the problem, in a normal setup hook rejections will always be handled. A repository to reproduce the problem can help finding the actual issue.

**Comment by shadowRR** [comment]
Should have done that in the first place ->[repo](https://github.com/shadowRR/feathers-errors-rejections)
I've just created a new feathers project with the last version available, added a `rejection` service, which has an async hook who's only purpose is to throw the same validations errors i have in my app. 

If you test it with the usual `yarn mocha`, i've added a simple test that just call the service, and you should see a `rejection handled!` message after the normal app log. That's because i've added a global `unhandledRejection` in the `app.js` file. If you remove it, you'll get the full error, unhandled.

**Comment by daffl** [comment]
Well, if you raise the error directly in a test, it does have to be handled. What I meant is that a call through an external provider (REST or Socket.io) will handle the exception but this is not the case if you are calling the code (service method) directly. It will behave just like any other JavaScript function that is throwing an error.

**Comment by shadowRR** [comment]
Yep, you're right, don't know what i was thinking there...

Anyway, after further investigations, i've ended up finding out where my issue was coming from, and it isn't feathers-errors but feathers-knex and more specifically the `transaction` hooks. Throwing out errors can, in some cases, avoid being properly handled. There's actually a pull request over there addressing this issue, but it's easy to avoid it in the meantime ;)

Thanks for the help (and thanks a lot for all of your work on feathers, awesome framework ❤️)
